@startuml

hide circle
title Classes

Class Користувач {
    логін: string
    пароль : string
}

Class ІнформаціяПроКористувача {
    хвороби : string
    name : string
}

Class ЗапитПроХарчування {
    текст_поради : string
}



ІнформаціяПроКористувача"1" --> "1"Користувач
Користувач"1" --> "*"ЗапитПроХарчування : отримує 




@enduml
