@startuml

title Usecase Diagram

left to right direction

actor Користувач

rectangle Software {

    usecase (Переглядати поради щодо безпечного поїдання їжі)
    usecase (Шукати інформацію про безпечні стосунки)
    usecase (Авторизація користувача для доступу до програмного продукту)

   (Переглядати поради щодо безпечного поїдання їжі) .> (Авторизація користувача для доступу до програмного продукту) : include
   (Шукати інформацію про безпечні стосунки) .> (Авторизація користувача для доступу до програмного продукту) : include
   Користувач -- (Переглядати поради щодо безпечного поїдання їжі)
   Користувач -- (Шукати інформацію про безпечні стосунки)
}

@enduml
